apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: zipkin
  name: zipkin
spec:
  ports:
    - name: "zipkin"
      port: 9411
      targetPort: 9411
  selector:
    io.kompose.service: zipkin
