apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: zipkin
  name: zipkin
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zipkin
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: zipkin
    spec:
      containers:
        - env:
            - name: STORAGE_TYPE
              value: mem
          image: openzipkin/zipkin
          name: zipkin
          ports:
            - containerPort: 9411
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: zipkin
  name: zipkin
  namespace: monitoring
spec:
  ports:
    - name: "zipkin"
      port: 9411
      targetPort: 9411
  selector:
    io.kompose.service: zipkin
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zipkin
  namespace: monitoring
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: zipkin.dh4r4pvj.ga
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zipkin
                port:
                  number: 9411
  tls:
  - hosts:
    - zipkin.dh4r4pvj.ga
    secretName: zipkin-cert
