resources:
  # limits:
  #   cpu: 10m
  #   memory: 30Mi
  requests:
    cpu: 10m
    memory: 30Mi

webhook:
  resources:
    requests:
      cpu: 10m
      memory: 30Mi

caninjector:
  resources:
    requests:
      cpu: 10m
      memory: 30Mi
