global:
  storageClass: efs-client
auth:
  # This is BAD to checking in password in plain text. OK for demo purposes.
  rootPassword: "checkout"
  database: checkout
rbac:
  create: true
metrics:
  enabled: true
primary:
  persistence:
    size: 250M
fullnameOverride: checkout-db