global:
  storageClass: efs-client
postgresqlDatabase: store
rbac:
  create: true
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: kube-prometheus-stack
persistence:
  size: 250M
resources:
  limits:
    memory: 512Mi
    cpu: 500m
  requests:
    memory: 256Mi
    cpu: 250m
fullnameOverride: store-db
  # This is BAD to checking in password in plain text. OK for demo purposes.
postgresqlPassword: storedb
postgresqlDatabase: store
