host:
  # docker0 is used
  iptables: true
  # flannel
  #interface: cni0
  # Calico
  interface: cali+
rbac:
  create: true

extraArgs:
  auto-discover-base-arn: 
  auto-discover-default-role: true

resources:
  limits:
    cpu: 4m
    memory: 16Mi
  requests:
    cpu: 4m
    memory: 16Mi
