dryRun: false

aws:
  region: "ap-south-1"

rbac:
  create: true

policy: "sync"

domainFilters:
  - dh4r4pvj.ga

# set via helm so that you can refer to role ARN from terraform
#podAnnotations:
#  iam.amazonaws.com/role: "YOUR_ROLE"

resources:
  limits:
    cpu: 5m
    memory: 50Mi
  requests:
    cpu: 3m
    memory: 50Mi

