grafana:
  ingress:
    enabled: true
    hosts:
    - grafana.dh4r4pvj.ga
    tls:
    - secretName: grafana-general-tls
      hosts:
      - grafana.dh4r4pvj.ga
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
prometheus:
  ingress:
    enabled: true
    hosts:
    - prometheus.dh4r4pvj.ga
    tls:
    - secretName: prometheus-general-tls
      hosts:
      - prometheus.dh4r4pvj.ga
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    paths:
    - /
    pathType: ImplementationSpecific
alertmanager:
  config:
    global:
      resolve_timeout: 5m
      slack_api_url: 'https://hooks.slack.com/services/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'
    route:
      group_by: ['job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'slack-notifications'
      routes:
      - match:
          alertname: Watchdog
        receiver: 'null'
    receivers:
    - name: 'null'
    - name: 'slack-notifications'
      slack_configs:
      - channel: '#k8s-alerts'
        send_resolved: true
        icon_url: https://avatars3.githubusercontent.com/u/3380462
        title: |-
          [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
          {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
            {{" "}}(
            {{- with .CommonLabels.Remove .GroupLabels.Names }}
              {{- range $index, $label := .SortedPairs -}}
                {{ if $index }}, {{ end }}
                {{- $label.Name }}="{{ $label.Value -}}"
              {{- end }}
            {{- end -}}
            )
          {{- end }}
        text: >-
          {{ range .Alerts -}}
          *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

          *Description:* {{ .Annotations.description }}

          *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
          {{ end }}
    templates:
    - '/etc/alertmanager/config/*.tmpl'
